// Regenerates the <link rel="modulepreload"> list in index.html so the
// browser fetches every ES module in parallel instead of discovering them one
// import level at a time. The list is the import graph reachable from
// src/main.js, so build/CI-only modules are never preloaded.
//
//   npm run preload            rewrite index.html
//   npm run preload -- --check exit 1 if index.html is out of date (CI)
//
// A stale list only costs latency; the page still works.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const ENTRY = 'src/main.js';
const START = '<!-- modulepreload:start (generated by scripts/preload.mjs) -->';
const END = '<!-- modulepreload:end -->';
const IMPORT_RE = /(?:^|\n)\s*(?:import|export)\s[^'"]*?from\s*['"](\.{1,2}\/[^'"]+)['"]|(?:^|\n)\s*import\s*['"](\.{1,2}\/[^'"]+)['"]/g;

async function graph(entry) {
  const seen = new Set();
  const visit = async (abs) => {
    if (seen.has(abs)) return;
    seen.add(abs);
    const code = await readFile(abs, 'utf8');
    for (const m of code.matchAll(IMPORT_RE)) await visit(resolve(dirname(abs), m[1] || m[2]));
  };
  await visit(join(root, entry));
  return [...seen].map((abs) => relative(root, abs).split(sep).join('/'));
}

const files = (await graph(ENTRY)).sort((a, b) => (a === ENTRY ? -1 : b === ENTRY ? 1 : a.localeCompare(b)));
const block = [START, ...files.map((f) => `  <link rel="modulepreload" href="${f}" />`), `  ${END}`].join('\n');

const indexPath = join(root, 'index.html');
const html = await readFile(indexPath, 'utf8');
const next = html.includes(START)
  ? html.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block.trimStart())
  : html.replace('  <link rel="stylesheet" href="src/styles.css" />', `  <link rel="stylesheet" href="src/styles.css" />\n  ${block}`);

if (process.argv.includes('--check')) {
  if (next !== html) {
    console.error('✗ index.html modulepreload list is out of date. Run `npm run preload` and commit the result.');
    if (process.env.GITHUB_ACTIONS === 'true') console.log('::error file=index.html,title=Stale modulepreload list::Run `npm run preload` and commit the result.');
    process.exit(1);
  }
  console.log(`✓ index.html preloads all ${files.length} modules reachable from ${ENTRY}`);
} else {
  await writeFile(indexPath, next);
  console.log(`index.html: ${files.length} modules preloaded`);
}
