// Regenerates the <link rel="modulepreload"> list in index.html so the
// browser fetches every ES module in parallel instead of discovering them
// one import level at a time. Run after adding or moving a module:
//   npm run preload
// A stale list only costs latency; the page still works.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const START = '<!-- modulepreload:start (generated by scripts/preload.mjs) -->';
const END = '<!-- modulepreload:end -->';

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else if (entry.name.endsWith('.js') && !p.includes(`${sep}cv${sep}`)) yield p;
  }
}

const files = ['assets/vendor/three.module.min.js'];
for await (const f of walk(join(root, 'src'))) files.push(relative(root, f).split(sep).join('/'));
files.sort((a, b) => (a === 'src/main.js' ? -1 : b === 'src/main.js' ? 1 : a.localeCompare(b)));

const block = [START, ...files.map((f) => `  <link rel="modulepreload" href="${f}" />`), `  ${END}`].join('\n');
const indexPath = join(root, 'index.html');
const html = await readFile(indexPath, 'utf8');
const next = html.includes(START)
  ? html.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block.trimStart())
  : html.replace('  <link rel="stylesheet" href="src/styles.css" />', `  <link rel="stylesheet" href="src/styles.css" />\n  ${block}`);
await writeFile(indexPath, next);
console.log(`index.html: ${files.length} modules preloaded`);
